os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - ls
  - bash miniconda.sh -b -p $HOME/miniconda
  - ls $HOME/miniconda/
  - ls $HOME/miniconda/etc
  - ls $HOME/miniconda/etc/profile.d
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda activate base
  - pip install .

script:
  - conda-app install mercurial
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cat $HOME/.bash_profile;
    else
      cat $HOME/.bashrc;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      . $HOME/.bash_profile;
    else
      . $HOME/.bashrc;
    fi
  - echo $PATH
  - which hg
  - hg version -v
  - cd $HOME
  - hg clone https://github.com/fluiddyn/conda-app.git
  - ls conda-app
