name: Test on Linux and MacOS

on:
  - push
  - pull_request

jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          python-version: 3.11
          auto-update-conda: true
          activate-environment: test

      - name: test install conda-app
        run: |
          which python
          python -m pip install -e .
          which conda-app

      - name: test install mercurial and pipx
        run: |
          conda-app install mercurial
          conda-app list
          conda-app install pipx python=3.12
          conda-app list
          conda-app uninstall pipx -y
          conda-app list

      - name: test installed mercurial
        run: |
          if [ -f $HOME/.bash_profile ]; then
            . $HOME/.bash_profile;
          else
            . $HOME/.bashrc;
          fi
          hg version -v
          hg debuginstall
          hg-setup -h
          hg-setup init --auto
          mkdir -p $HOME/tmp
          cd $HOME/tmp
          hg clone https://github.com/fluiddyn/conda-app.git
          cd conda-app
